name: build
on:
  push:
    branches: [ "master" ]
    paths-ignore: [ "*.md" ]
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * 1'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3

      - name: Guess the registry
        shell: bash
        run: |
          CONTAINER_REGISTRY="${{ vars.CONTAINER_REGISTRY }}"
          CONTAINER_REGISTRY=${CONTAINER_REGISTRY:-$(cut -d/ -f3 <<<"${{ github.server_url }}")}
          echo "CONTAINER_REGISTRY=${CONTAINER_REGISTRY/#github.com/ghcr.io}" >> $GITHUB_ENV
    
      - name: Log in to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.CONTAINER_REGISTRY }}
          username: ${{ vars.CONTAINER_REGISTRY_USERNAME || github.actor }}
          password: ${{ secrets.CONTAINER_REGISTRY_TOKEN || github.token }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          pull: true
          tags: |
            ${{ env.CONTAINER_REGISTRY }}/${{ vars.CONTAINER_REPOSITORY || github.repository }}:latest
            ${{ env.CONTAINER_REGISTRY }}/${{ vars.CONTAINER_REPOSITORY || github.repository }}:${{ github.sha }}
