name: build
on:
  push:
    branches: [ "main" ]
    paths-ignore: [ "*.md" ]
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * 1'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3

      - name: Guess the registry
        shell: bash
        run: |
          CONTAINER_REGISTRY="${{ vars.CONTAINER_REGISTRY }}"
          CONTAINER_REGISTRY=${CONTAINER_REGISTRY:-$(cut -d/ -f3 <<<"${{ github.server_url }}")}
          echo "CONTAINER_REGISTRY=${CONTAINER_REGISTRY/#github.com/ghcr.io}" >> $GITHUB_ENV
    
      - name: Log in to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.CONTAINER_REGISTRY }}
          username: ${{ vars.CONTAINER_REGISTRY_USERNAME || github.actor }}
          password: ${{ secrets.CONTAINER_REGISTRY_TOKEN || github.token }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          cache-from: type=registry,ref=${{ env.CONTAINER_REGISTRY }}/${{ vars.CONTAINER_REPOSITORY || github.repository }}:buildcache
          cache-to: type=registry,ref=${{ env.CONTAINER_REGISTRY }}/${{ vars.CONTAINER_REPOSITORY || github.repository }}:buildcache,mode=max
          push: true
          pull: true
          tags: |
            ${{ env.CONTAINER_REGISTRY }}/${{ vars.CONTAINER_REPOSITORY || github.repository }}:latest
          # ${{ env.CONTAINER_REGISTRY }}/${{ vars.CONTAINER_REPOSITORY || github.repository }}:${{ github.sha }}

      # - name: Cleanup old images
      #   if: env.CONTAINER_REGISTRY == 'ghcr.io'
      #   uses: actions/delete-package-versions@v5
      #   with:
      #     package-name: ${{ vars.CONTAINER_REPOSITORY || github.repository }}
      #     package-type: container
      #     token: ${{ secrets.CONTAINER_REGISTRY_TOKEN || github.token }}
      #     min-versions-to-keep: 2
      #     ignore-versions: latest
      #     delete-only-untagged-versions: false
